manifest_version = 1

[module]
id = "disposable-voice-channels"
name = "Disposable Voice Channels"
description = "Allows server members to join a specific voice channel that creates another voice channel that they have permission to manage and disconnect other users from."
version = "1.0"
license = "GNU GPLv3"
authors = ["peeblyweeb"]
